CREATE TABLE "adversary_previews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"subtype" text,
	"image" text,
	"artist" text,
	"credits" text,
	"tier" integer,
	"description" text,
	"sub_description" text,
	"experience" text,
	"text" text,
	"difficulty" text,
	"hp" integer,
	"stress" integer,
	"thresholds" "point",
	"attack" text,
	"weapon" text,
	"distance" text,
	"damage_type" text,
	"damage_amount" text,
	"potential" text
);
--> statement-breakpoint
CREATE TABLE "card_previews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"image" text,
	"text" text,
	"artist" text,
	"credits" text,
	"subtype" text,
	"subtitle" text,
	"level" integer,
	"stress" integer,
	"evasion" integer,
	"thresholds" "point",
	"thresholds_enabled" boolean DEFAULT false,
	"tier" integer,
	"tier_enabled" boolean DEFAULT false,
	"hands" integer,
	"hands_enabled" boolean DEFAULT false,
	"armor" integer,
	"armor_enabled" boolean DEFAULT false,
	"domain_primary" text,
	"domain_primary_color" text,
	"domain_primary_icon" text,
	"domain_secondary" text,
	"domain_secondary_color" text,
	"domain_secondary_icon" text
);